FROM nginx:alpine

# 删除默认的nginx静态资源
RUN rm -rf /usr/share/nginx/html/*

# 复制静态文件到Nginx服务目录
COPY ./index /usr/share/nginx/html/index
COPY ./ai /usr/share/nginx/html/ai
COPY ./analysis /usr/share/nginx/html/analysis
COPY ./upload /usr/share/nginx/html/upload
COPY ./public /usr/share/nginx/html/public

# 复制自定义nginx配置
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 暴露80端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 